/**
 * Keywords por país para Careerjet — pool masivo
 * Estructura: { [countryCode]: { name, keywords (40-110), cities (15-20) } }
 * Cada keyword extrae ~100 ofertas × 5 páginas Careerjet
 */
export const CAREERJET_COUNTRIES: Record<string, { name: string; keywords: string[]; cities: string[] }> = {
  us: {
    name: "Estados Unidos",
    keywords: [
      "software engineer", "registered nurse", "truck driver", "teacher", "accountant",
      "electrician", "retail manager", "data analyst", "sales representative", "mechanic",
      "pharmacist", "physical therapist", "dental hygienist", "web developer", "project manager",
      "welder", "carpenter", "HVAC technician", "plumber", "forklift operator",
      "warehouse worker", "customer service", "administrative assistant", "security guard",
      "delivery driver", "logistics coordinator", "supply chain manager", "operations manager",
      "financial analyst", "HR manager", "marketing manager", "data scientist",
      "devops engineer", "full stack developer", "cloud engineer", "cyber security analyst",
      "medical assistant", "surgical technologist", "home health aide", "paramedic",
      "construction labourer", "heavy equipment operator", "production supervisor",
      "quality control inspector", "CNC machinist", "call center agent", "janitor",
      "landscaper", "maintenance technician", "social worker",
    ],
    cities: ["New York", "Los Angeles", "Chicago", "Houston", "Miami", "Seattle", "Boston",
      "Atlanta", "Dallas", "Denver", "Austin", "San Francisco", "Phoenix", "Portland",
      "Nashville", "Philadelphia", "San Diego", "Charlotte", "Orlando", "Tampa"],
  },
  uk: {
    name: "Reino Unido",
    keywords: [
      "software engineer", "nurse", "teacher", "electrician", "HGV driver", "accountant",
      "chef", "project manager", "data analyst", "plumber", "care assistant", "sales manager",
      "web developer", "HR manager", "marketing manager", "welder", "carpenter",
      "delivery driver", "forklift driver", "warehouse operative", "customer service",
      "administrator", "security guard", "cleaner", "logistics coordinator",
      "supply chain manager", "operations manager", "financial analyst", "data scientist",
      "devops engineer", "full stack developer", "cloud engineer", "cyber security analyst",
      "teaching assistant", "social worker", "production operative", "maintenance engineer",
      "call centre agent", "labourer", "receptionist", "retail assistant",
      "kitchen assistant", "bar staff", "support worker", "class 1 driver",
    ],
    cities: ["London", "Manchester", "Birmingham", "Leeds", "Glasgow", "Liverpool",
      "Edinburgh", "Bristol", "Sheffield", "Cardiff", "Newcastle", "Nottingham",
      "Belfast", "Leicester", "Brighton", "Southampton", "Portsmouth", "Oxford",
      "Cambridge", "Norwich"],
  },
  au: {
    name: "Australia",
    keywords: [
      "software engineer", "registered nurse", "electrician", "teacher", "chef",
      "accountant", "project manager", "data analyst", "diesel mechanic", "truck driver",
      "aged care worker", "web developer", "retail manager", "mining engineer", "civil engineer",
      "welder", "carpenter", "plumber", "HVAC technician", "forklift driver",
      "warehouse worker", "customer service", "administrative assistant", "security guard",
      "delivery driver", "logistics coordinator", "HR manager", "social worker",
      "physiotherapist", "occupational therapist", "speech pathologist", "paramedic",
      "early childhood educator", "labourer", "cleaner", "barista", "waiter",
      "kitchen hand", "receptionist", "sales representative",
    ],
    cities: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast",
      "Canberra", "Newcastle", "Hobart", "Darwin", "Cairns", "Townsville", "Geelong",
      "Wollongong", "Sunshine Coast", "Central Coast", "Toowoomba", "Ballarat",
      "Bendigo", "Launceston"],
  },
  ca: {
    name: "Canadá",
    keywords: [
      "software engineer", "registered nurse", "electrician", "teacher", "truck driver",
      "accountant", "chef", "project manager", "data analyst", "heavy duty mechanic",
      "web developer", "HR manager", "retail manager", "financial analyst", "civil engineer",
      "welder", "carpenter", "early childhood educator", "social worker",
      "administrative assistant", "warehouse worker", "delivery driver", "security guard",
      "construction labourer", "customer service", "plumber", "HVAC technician",
      "forklift operator", "logistics coordinator", "supply chain manager",
      "mining engineer", "oil field worker", "pharmacist", "physiotherapist",
      "dental hygienist", "paramedic", "home care aide", "cleaner", "painter",
      "production worker", "call centre agent", "receptionist",
    ],
    cities: ["Toronto", "Vancouver", "Montreal", "Calgary", "Edmonton", "Ottawa",
      "Quebec City", "Winnipeg", "Hamilton", "Kitchener", "London Ontario", "Halifax",
      "Victoria", "Saskatoon", "Mississauga", "Brampton", "Surrey", "Laval",
      "Markham", "Gatineau"],
  },
  de: {
    name: "Alemania",
    keywords: [
      "Krankenpfleger", "Softwareentwickler", "Elektriker", "Lehrer", "LKW Fahrer",
      "Buchhalter", "Koch", "Projektmanager", "Datenanalyst", "Klempner",
      "Altenpfleger", "Verkaufsleiter", "Webentwickler", "Personalmanager",
      "Maschinenbauingenieur", "Erzieher", "Physiotherapeut", "Arzthelferin",
      "Lagerarbeiter", "Reinigungskraft", "Schweisser", "Zimmermann",
      "Maler", "Gabelstaplerfahrer", "Kundendienst", "Burokaufmann",
      "Sicherheitsdienst", "Zusteller", "Logistikkoordinator", "Supply Chain Manager",
      "Finanzanalyst", "Data Scientist", "DevOps Engineer", "Full Stack Entwickler",
      "Cloud Engineer", "Cyber Security", "Medizinischer Fachangestellter",
      "Sozialarbeiter", "Produktionsmitarbeiter", "Instandhalter",
      "Call Center Agent", "Bauarbeiter", "Empfangskraft", "Einzelhandel",
      "Kuchenhilfe", "Kellner", "Pflegehelfer", "Betriebswirt",
    ],
    cities: ["Berlin", "Munchen", "Hamburg", "Frankfurt", "Koln", "Stuttgart",
      "Dusseldorf", "Leipzig", "Dortmund", "Essen", "Bremen", "Dresden",
      "Hannover", "Nurnberg", "Bonn", "Mannheim", "Karlsruhe", "Augsburg",
      "Wiesbaden", "Munster"],
  },
  fr: {
    name: "Francia",
    keywords: [
      "infirmier", "developpeur logiciel", "electricien", "enseignant", "chauffeur",
      "comptable", "chef", "gestionnaire de projet", "analyste de donnees", "plombier",
      "aide soignant", "directeur commercial", "developpeur web", "responsable RH",
      "ingenieur mecanique", "educateur", "kinesitherapeute", "assistant medical",
      "magasinier", "agent entretien", "soudeur", "menuisier", "cariste",
      "service client", "assistant administratif", "agent securite", "livreur",
      "coordinateur logistique", "analyste financier", "data scientist",
      "devops", "cybersecurite", "assistant dentaire", "travailleur social",
      "operateur production", "technicien maintenance", "conseiller clientele",
      "ouvrier batiment", "receptionniste", "vendeur", "commis cuisine",
      "serveur", "auxiliaire vie", "commercial",
    ],
    cities: ["Paris", "Lyon", "Marseille", "Toulouse", "Nice", "Nantes",
      "Strasbourg", "Montpellier", "Bordeaux", "Lille", "Rennes", "Reims",
      "Grenoble", "Dijon", "Toulon", "Saint-Etienne", "Le Havre", "Angers",
      "Nimes", "Clermont-Ferrand"],
  },
  nl: {
    name: "Países Bajos",
    keywords: [
      "verpleegkundige", "software ontwikkelaar", "elektricien", "leraar",
      "vrachtwagenchauffeur", "accountant", "chef kok", "projectmanager", "data analist",
      "loodgieter", "verzorgende", "sales manager", "web ontwikkelaar", "HR manager",
      "werktuigbouwkundig ingenieur", "pedagogisch medewerker", "fysiotherapeut",
      "doktersassistent", "magazijnmedewerker", "schoonmaker", "lasser", "timmerman",
      "heftruckchauffeur", "klantenservice", "administratief medewerker", "beveiliger",
      "bezorger", "logistiek coördinator", "financieel analist", "data scientist",
      "devops engineer", "cyber security", "tandartsassistent", "sociaal werker",
      "productiemedewerker", "onderhoudsmonteur", "callcenter medewerker", "bouwvakker",
      "receptioniste", "winkelmedewerker", "keukenhulp", "ober",
    ],
    cities: ["Amsterdam", "Rotterdam", "Den Haag", "Utrecht", "Eindhoven", "Groningen",
      "Tilburg", "Almere", "Breda", "Nijmegen", "Arnhem", "Haarlem",
      "Enschede", "Maastricht", "Leiden", "Dordrecht", "Apeldoorn", "Amersfoort",
      "Zwolle", "Den Bosch"],
  },
  it: {
    name: "Italia",
    keywords: [
      "infermiere", "sviluppatore software", "elettricista", "insegnante", "autista",
      "contabile", "chef", "project manager", "analista dati", "idraulico",
      "assistente sanitario", "responsabile vendite", "sviluppatore web", "responsabile HR",
      "ingegnere meccanico", "educatore", "fisioterapista", "assistente medico",
      "magazziniere", "addetto pulizie", "saldatore", "falegname", "carrellista",
      "servizio clienti", "assistente amministrativo", "guardia giurata", "corriere",
      "coordinatore logistico", "analista finanziario", "data scientist",
      "devops", "cyber security", "assistente dentale", "lavoratore sociale",
      "operaio produzione", "tecnico manutenzione", "operatore call center",
      "muratore", "receptionist", "commesso", "aiuto cuoco", "cameriere",
      "badante", "rappresentante commerciale",
    ],
    cities: ["Roma", "Milano", "Napoli", "Torino", "Palermo", "Genova", "Bologna",
      "Firenze", "Catania", "Bari", "Venezia", "Verona", "Messina", "Padova",
      "Trieste", "Brescia", "Parma", "Modena", "Reggio Calabria", "Cagliari"],
  },
  es: {
    name: "España",
    keywords: [
      "enfermero", "desarrollador software", "electricista", "profesor", "conductor",
      "contable", "cocinero", "gestor proyectos", "analista datos", "fontanero",
      "auxiliar enfermeria", "comercial", "desarrollador web", "responsable RRHH",
      "ingeniero mecanico", "educador", "fisioterapeuta", "auxiliar administrativo",
      "mozo almacen", "limpiador", "soldador", "carpintero", "carretillero",
      "atencion cliente", "administrativo", "vigilante seguridad", "repartidor",
      "coordinador logistica", "analista financiero", "data scientist",
      "devops", "ciberseguridad", "auxiliar dental", "trabajador social",
      "operario produccion", "tecnico mantenimiento", "teleoperador",
      "albanil", "recepcionista", "dependiente", "ayudante cocina", "camarero",
      "cuidador", "jefe ventas", "marketing digital",
    ],
    cities: ["Madrid", "Barcelona", "Valencia", "Sevilla", "Zaragoza", "Malaga",
      "Murcia", "Palma", "Bilbao", "Alicante", "Cordoba", "Valladolid", "Vigo",
      "Gijon", "Granada", "La Coruna", "Vitoria", "Oviedo", "Santander", "Pamplona"],
  },
  se: {
    name: "Suecia",
    keywords: [
      "sjukskoterska", "mjukvaruutvecklare", "elektriker", "larare", "lastbilsforare",
      "revisor", "kock", "projektledare", "dataanalytiker", "rorlaggare",
      "underskoterska", "saljchef", "webbutvecklare", "HR chef", "maskiningenjor",
      "forskollarare", "fysioterapeut", "lakarsekreterare", "lagerarbetare", "stadare",
      "svetsare", "snickare", "truckforare", "kundtjanst", "administrator",
      "vaktare", "bud", "logistikkoordinator", "finansanalytiker",
      "data scientist", "devops", "cybersakerhet", "tandskoterska",
      "socialarbetare", "produktionsmedarbetare", "underhallstekniker",
    ],
    cities: ["Stockholm", "Goteborg", "Malmo", "Uppsala", "Linkoping", "Orebro",
      "Vasteras", "Helsingborg", "Norrkoping", "Jonkoping", "Umea", "Lund",
      "Boras", "Sundsvall", "Gavle"],
  },
  ch: {
    name: "Suiza",
    keywords: [
      "Krankenpfleger", "infirmier", "Softwareentwickler", "developpeur logiciel",
      "Elektriker", "electricien", "Lehrer", "enseignant", "Buchhalter", "comptable",
      "Koch", "chef", "Projektmanager", "gestionnaire de projet", "Webentwickler",
      "developpeur web", "Verkaufsleiter", "sales manager", "Lagerarbeiter",
      "magasinier", "Reinigungskraft", "agent entretien", "Schweisser", "soudeur",
      "Kundendienst", "service client", "Finanzanalyst", "analyste financier",
      "devops", "cybersecurite", "Sozialarbeiter", "travailleur social",
    ],
    cities: ["Zurich", "Geneve", "Basel", "Bern", "Lausanne", "Winterthur",
      "Luzern", "St. Gallen", "Lugano", "Biel", "Thun", "Koniz",
      "La Chaux-de-Fonds", "Fribourg", "Schaffhausen"],
  },
  be: {
    name: "Bélgica",
    keywords: [
      "verpleegkundige", "infirmier", "software ontwikkelaar", "developpeur logiciel",
      "elektricien", "electricien", "leraar", "enseignant", "accountant", "comptable",
      "projectmanager", "gestionnaire de projet", "web ontwikkelaar", "developpeur web",
      "magazijnmedewerker", "magasinier", "schoonmaker", "agent entretien",
      "lasser", "soudeur", "klantenservice", "service client", "boekhouder",
      "HR manager", "technieker", "technicien", "verkoper", "vendeur",
    ],
    cities: ["Brussels", "Antwerpen", "Gent", "Charleroi", "Liege", "Brugge",
      "Namur", "Leuven", "Mons", "Aalst", "Mechelen", "La Louviere",
      "Kortrijk", "Hasselt", "Ostend"],
  },
  pt: {
    name: "Portugal",
    keywords: [
      "enfermeiro", "programador", "eletricista", "professor", "motorista",
      "contabilista", "cozinheiro", "gestor projeto", "analista dados", "canalizador",
      "auxiliar enfermagem", "comercial", "programador web", "gestor RH",
      "engenheiro mecanico", "educador", "fisioterapeuta", "assistente administrativo",
      "armazem", "empregado limpeza", "soldador", "carpinteiro", "empilhador",
      "apoio cliente", "seguranca", "estafeta", "logistica", "analista financeiro",
      "rececionista", "lojista", "ajudante cozinha", "empregado mesa",
    ],
    cities: ["Lisboa", "Porto", "Braga", "Coimbra", "Funchal", "Amadora",
      "Vila Nova de Gaia", "Setubal", "Aveiro", "Faro", "Evora", "Viseu",
      "Leiria", "Guimaraes", "Viana do Castelo"],
  },
  ie: {
    name: "Irlanda",
    keywords: [
      "software engineer", "nurse", "teacher", "electrician", "driver", "accountant",
      "chef", "project manager", "data analyst", "plumber", "care assistant",
      "sales manager", "web developer", "HR manager", "marketing manager",
      "welder", "carpenter", "warehouse operative", "customer service",
      "administrator", "security guard", "cleaner", "delivery driver",
      "logistics coordinator", "financial analyst", "devops engineer",
      "full stack developer", "cyber security analyst", "medical assistant",
      "social worker", "production operative", "maintenance technician",
      "call centre agent", "labourer", "receptionist", "retail assistant",
      "kitchen porter", "bar staff", "fitness instructor",
    ],
    cities: ["Dublin", "Cork", "Limerick", "Galway", "Waterford", "Drogheda",
      "Kilkenny", "Dundalk", "Swords", "Bray", "Navan", "Ennis", "Tralee",
      "Carlow", "Athlone"],
  },
  no: {
    name: "Noruega",
    keywords: [
      "sykepleier", "programvareutvikler", "elektriker", "laerer", "lastebilsjafor",
      "regnskapsforer", "kokk", "prosjektleder", "dataanalytiker", "rorlegger",
      "helsefagarbeider", "salgsleder", "webutvikler", "HR leder", "maskiningenior",
      "barnehagelaerer", "fysioterapeut", "legesekretaer", "lagerarbeider", "renholder",
      "sveiser", "tomrer", "truckforer", "kundeservice", "administrasjon",
      "sikkerhetsvakt", "bud", "logistikkoordinator", "finansanalytiker",
    ],
    cities: ["Oslo", "Bergen", "Trondheim", "Stavanger", "Drammen", "Fredrikstad",
      "Kristiansand", "Sandnes", "Tromso", "Sarpsborg", "Skien", "Alesund",
      "Sandefjord", "Haugesund", "Bodo"],
  },
  dk: {
    name: "Dinamarca",
    keywords: [
      "sygeplejerske", "softwareudvikler", "elektriker", "laerer", "lastbilchauffor",
      "bogholder", "kok", "projektleder", "dataanalytiker", "VVS montor",
      "social og sundhedsassistent", "salgschef", "webudvikler", "HR chef",
      "maskiningenior", "paedagog", "fysioterapeut", "laegesekretaer",
      "lagermedarbejder", "rengoringsassistent", "svejser", "tomrer",
      "truckforer", "kundeservice", "administration", "sikkerhedsvagt",
      "bud", "logistikkoordinator", "finansanalytiker",
    ],
    cities: ["Kobenhavn", "Aarhus", "Odense", "Aalborg", "Esbjerg", "Randers",
      "Kolding", "Horsens", "Vejle", "Roskilde", "Herning", "Silkeborg",
      "Naestved", "Frederiksberg", "Viborg"],
  },
  at: {
    name: "Austria",
    keywords: [
      "Krankenpfleger", "Softwareentwickler", "Elektriker", "Lehrer", "LKW Fahrer",
      "Buchhalter", "Koch", "Projektmanager", "Datenanalyst", "Installateur",
      "Altenpfleger", "Verkaufsleiter", "Webentwickler", "Personalmanager",
      "Maschinenbauingenieur", "Erzieher", "Physiotherapeut", "Arzthelferin",
      "Lagerarbeiter", "Reinigungskraft", "Schweisser", "Zimmermann",
      "Maler", "Gabelstaplerfahrer", "Kundendienst", "Burokaufmann",
      "Zusteller", "Logistikkoordinator", "Finanzanalyst", "Data Scientist",
    ],
    cities: ["Wien", "Graz", "Linz", "Salzburg", "Innsbruck", "Klagenfurt",
      "Villach", "Wels", "Sankt Polten", "Dornbirn", "Wiener Neustadt",
      "Steyr", "Feldkirch", "Bregenz", "Leoben"],
  },
  fi: {
    name: "Finlandia",
    keywords: [
      "sairaanhoitaja", "ohjelmistokehittaja", "sahkoasentaja", "opettaja",
      "kuorma-autonkuljettaja", "kirjanpitaja", "kokki", "projektipaallikko",
      "data analyytikko", "putkimies", "lahihoitaja", "myyntipaallikko",
      "web kehittaja", "HR paallikko", "koneinsinoori", "lastentarhanopettaja",
      "fysioterapeutti", "laakarin sihteeri", "varastotyontekija", "siivooja",
      "hitsaaja", "kirvesmies", "trukkikuski", "asiakaspalvelu",
      "toimistotyontekija", "vartija", "lahetti", "logistiikkakoordinaattori",
    ],
    cities: ["Helsinki", "Espoo", "Tampere", "Vantaa", "Turku", "Oulu",
      "Jyvaskyla", "Lahti", "Kuopio", "Pori", "Joensuu", "Lappeenranta",
      "Hameenlinna", "Vaasa", "Rovaniemi"],
  },
  nz: {
    name: "Nueva Zelanda",
    keywords: [
      "software engineer", "registered nurse", "electrician", "teacher", "truck driver",
      "accountant", "chef", "project manager", "data analyst", "plumber",
      "aged care worker", "sales manager", "web developer", "HR manager", "civil engineer",
      "welder", "carpenter", "forklift operator", "warehouse worker",
      "customer service", "administrator", "security guard", "cleaner",
      "delivery driver", "logistics coordinator", "financial analyst",
      "social worker", "physiotherapist", "early childhood teacher",
      "maintenance technician", "receptionist", "retail assistant",
      "kitchen hand", "barista", "farm worker",
    ],
    cities: ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga",
      "Dunedin", "Palmerston North", "Napier", "Nelson", "Rotorua",
      "New Plymouth", "Whangarei", "Invercargill", "Whanganui", "Gisborne"],
  },
  pl: {
    name: "Polonia",
    keywords: [
      "pielegniarka", "programista", "elektryk", "nauczyciel", "kierowca",
      "ksiegowy", "kucharz", "kierownik projektu", "analityk danych", "hydraulik",
      "opiekun", "kierownik sprzedazy", "web developer", "kierownik HR",
      "inzynier mechanik", "wychowawca", "fizjoterapeuta", "asystent medyczny",
      "magazynier", "sprzataczka", "spawacz", "stolarz", "operator wozka",
      "obsluga klienta", "administracja", "ochroniarz", "kurier",
      "koordynator logistyki", "analityk finansowy", "recepcjonista",
    ],
    cities: ["Warszawa", "Krakow", "Lodz", "Wroclaw", "Poznan", "Gdansk",
      "Szczecin", "Bydgoszcz", "Lublin", "Bialystok", "Katowice", "Gdynia",
      "Czestochowa", "Radom", "Torun"],
  },
  gr: {
    name: "Grecia",
    keywords: [
      "software engineer", "nurse", "teacher", "electrician", "driver", "accountant",
      "chef", "project manager", "data analyst", "plumber", "web developer",
      "HR manager", "sales manager", "mechanical engineer", "civil engineer",
      "welder", "carpenter", "warehouse worker", "customer service", "administrator",
      "security guard", "cleaner", "delivery driver", "logistics coordinator",
      "financial analyst", "devops engineer", "full stack developer", "cyber security",
      "receptionist", "waiter", "bartender", "hotel staff", "tourism", "retail assistant",
    ],
    cities: ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa", "Volos",
      "Ioannina", "Kavala", "Chania", "Rhodes", "Corfu", "Kalamata",
      "Alexandroupoli", "Trikala", "Serres"],
  },
  cz: {
    name: "República Checa",
    keywords: [
      "software engineer", "nurse", "teacher", "electrician", "driver", "accountant",
      "chef", "project manager", "data analyst", "plumber", "web developer",
      "HR manager", "sales manager", "mechanical engineer", "welder", "carpenter",
      "warehouse worker", "customer service", "administrator", "security guard",
      "cleaner", "delivery driver", "logistics coordinator", "financial analyst",
      "devops engineer", "full stack developer", "cyber security", "receptionist",
      "retail assistant", "production operator", "maintenance technician",
    ],
    cities: ["Prague", "Brno", "Ostrava", "Plzen", "Liberec", "Olomouc",
      "Ceske Budejovice", "Hradec Kralove", "Usti nad Labem", "Pardubice",
      "Zlin", "Havirov", "Kladno", "Most", "Opava"],
  },
  hu: {
    name: "Hungría",
    keywords: [
      "software engineer", "nurse", "teacher", "electrician", "driver", "accountant",
      "chef", "project manager", "data analyst", "plumber", "web developer",
      "HR manager", "sales manager", "mechanical engineer", "welder", "carpenter",
      "warehouse worker", "customer service", "administrator", "security guard",
      "cleaner", "delivery driver", "logistics coordinator", "financial analyst",
      "devops engineer", "full stack developer", "cyber security", "receptionist",
      "retail assistant", "production operator",
    ],
    cities: ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pecs", "Gyor",
      "Nyiregyhaza", "Kecskemet", "Szekesfehervar", "Szombathely",
      "Szolnok", "Tatabanya", "Eger", "Bekescsaba", "Zalaegerszeg"],
  },
  ro: {
    name: "Rumanía",
    keywords: [
      "software engineer", "nurse", "teacher", "electrician", "driver", "accountant",
      "chef", "project manager", "data analyst", "plumber", "web developer",
      "HR manager", "sales manager", "mechanical engineer", "civil engineer",
      "welder", "carpenter", "warehouse worker", "customer service", "administrator",
      "security guard", "cleaner", "delivery driver", "logistics coordinator",
      "financial analyst", "devops engineer", "full stack developer", "cyber security",
      "receptionist", "call center agent", "retail assistant", "production operator",
    ],
    cities: ["Bucharest", "Cluj-Napoca", "Timisoara", "Iasi", "Constanta",
      "Brasov", "Craiova", "Galati", "Ploiesti", "Oradea", "Sibiu",
      "Arad", "Pitesti", "Bacau", "Targu Mures"],
  },
};
